export enum SORT {
  RANK_ASC = "RANASC",
  RANK_DESC = "RANDSC",
  NAME_ASC = "NAMASC",
  NAME_DESC = "NAMDSC",
  VOLUME_ASC = "VOLASC",
  VOLUME_DESC = "VOLDSC",
  PRICE_ASC = "PRIASC",
  PRICE_DESC = "PRIDSC",
  PERCENTAGE_ASC = "PERASC",
  PERCENTAGE_DESC = "PERDSC",
}
